In [1]:
# numpy作业： 高中体测数据转换

In [247]:
import numpy as np
import pandas as pd

In [275]:
# 读取成绩表  两个工作表分别存入两个变量
data_man = pd.read_excel('./18级高一体测成绩汇总.xls') # 默认加载第一个工作表
data_woman = pd.read_excel('./18级高一体测成绩汇总.xls',sheet_name = 1) # 指定加载第二个工作表
display(data_man,data_woman)

     班级 性别 男1000米跑  男50米跑    男跳远  男体前屈  男引体  男肺活量     身高    体重  BMI
0     1  男    4'13   8.88  195.0    12    1  2785  170.0  72.6    0
1     1  男    4'16   7.70  225.0    11    7  3133  174.0  52.7    0
2     1  男    4'09   8.45  218.0    14    1  3901  169.0  46.5    0
3     1  男    4'21   8.05  206.0    13    1  4946  183.0  79.7    0
4     1  男    3'44   7.52  210.0    13    9  3538  171.0  54.7    0
..   .. ..     ...    ...    ...   ...  ...   ...    ...   ...  ...
472  17  男    4'23   8.27  208.0    10    0  4647  176.0  69.5    0
473  17  男    5'19   9.55  210.0    15    6  7042  177.0  76.0    0
474  17  男    3'25   7.50  252.0    13   13  5755  181.0  65.0    0
475  17  男    4'39   7.81  208.0    14   11  5688  172.0  51.7    0
476  17  男       0   0.00    0.0     0    0     0    0.0   0.0    0

[477 rows x 11 columns]

     班级 性别  女800米跑  女50米跑    女跳远  女体前屈  女仰卧  女肺活量     身高    体重  BMI
0     1  女    3.22   9.32  185.0    16   48  3775  163.0  51.3    0
1     1  女    4.59  11.44  148.0     9   29  3683  163.0  66.6    0
2     1  女    3.46  13.40  150.0     7   40  3331  157.0  60.0    0
3     1  女    3.39   9.52  172.0    21   46  3701  160.0  50.7    0
4     1  女    3.43   9.79  145.0     8   34  3592  167.0  63.9    0
..   .. ..     ...    ...    ...   ...  ...   ...    ...   ...  ...
588  17  女    3.51   9.60  150.0    24   41  2255  158.0  49.0    0
589  17  女    4.00  10.18  150.0    13   36  2937  161.0  55.7    0
590  17  女    3.45  10.18  152.0    15   35  2592  165.0  48.6    0
591  17  女    4.01   9.67  165.0    10   41  1829  154.0  43.6    0
592  17  女    4.48   9.09  180.0    10   46  2962  162.0  55.3    0

[593 rows x 11 columns]

In [276]:
# 读取评分标准
data_mark = pd.read_excel('./体侧成绩评分表.xls',header = [0,1]) # header=[0,1]表示多层列索引
data_mark

    男肺活量       女肺活量      男50米跑      女50米跑       男体前屈       ...  女跳远       \
      成绩   分数    成绩   分数    成绩   分数    成绩   分数    成绩   分数  ...   成绩   分数
0   4540  100  3150  100   7.1  100   7.8  100  23.6  100  ...  204  100
1   4420   95  3100   95   7.2   95   7.9   95  21.5   95  ...  198   95
2   4300   90  3050   90   7.3   90   8.0   90  19.4   90  ...  192   90
3   4050   85  2900   85   7.4   85   8.3   85  17.2   85  ...  185   85
4   3800   80  2750   80   7.5   80   8.6   80  15.0   80  ...  178   80
5   3680   78  2650   78   7.7   78   8.8   78  13.6   78  ...  175   78
6   3560   76  2550   76   7.9   76   9.0   76  12.2   76  ...  172   76
7   3440   74  2450   74   8.1   74   9.2   74  10.8   74  ...  169   74
8   3320   72  2350   72   8.3   72   9.4   72   9.4   72  ...  166   72
9   3200   70  2250   70   8.5   70   9.6   70   8.0   70  ...  163   70
10  3080   68  2150   68   8.7   68   9.8   68   6.6   68  ...  160   68
11  2960   66  2050   66   8.9   66  10.0   66   5.2   66  ...  157   66
12  2840   64  1950   64   9.1   64  10.2   64   3.8   64  ...  154   64
13  2720   62  1850   62   9.3   62  10.4   62   2.4   62  ...  151   62
14  2600   60  1750   60   9.5   60  10.6   60   1.0   60  ...  148   60
15  2470   50  1710   50   9.7   50  10.8   50   0.0   50  ...  143   50
16  2340   40  1670   40   9.9   40  11.0   40  -1.0   40  ...  138   40
17  2210   30  1630   30  10.1   30  11.2   30  -2.0   30  ...  133   30
18  2080   20  1590   20  10.3   20  11.4   20  -3.0   20  ...  128   20
19  1950   10  1550   10  10.5   10  11.6   10  -4.0   10  ...  123   10

     男引体      女仰卧      男1000米跑      女800米跑
      成绩   分数  成绩   分数      成绩   分数     成绩   分数
0   16.0  100  53  100   3'30"  100  3'24"  100
1   15.0   95  51   95   3'35"   95  3'30"   95
2   14.0   90  49   90   3'40"   90  3'36"   90
3   13.0   85  46   85   3'47"   85  3'43"   85
4   12.0   80  43   80   3'55"   80  3'50"   80
5    NaN   78  41   78   4'00"   78  3'55"   78
6   11.0   76  39   76   4'05"   76  4'00"   76
7    NaN   74  37   74   4'10"   74  4'05"   74
8   10.0   72  35   72   4'15"   72  4'10"   72
9    NaN   70  33   70   4'20"   70  4'15"   70
10   9.0   68  31   68   4'25"   68  4'20"   68
11   NaN   66  29   66   4'30"   66  4'25"   66
12   8.0   64  27   64   4'35"   64  4'30"   64
13   NaN   62  25   62   4'40"   62  4'35"   62
14   7.0   60  23   60   4'45"   60  4'40"   60
15   6.0   50  21   50   5'05"   50  4'50"   50
16   5.0   40  19   40   5'25"   40  5'00"   40
17   4.0   30  17   30   5'45"   30  5'10"   30
18   3.0   20  15   20   6'05"   20  5'20"   20
19   2.0   10  13   10   6'25"   10  5'30"   10

[20 rows x 24 columns]

In [277]:
data_man.dtypes

班级           int64
性别          object
男1000米跑     object
男50米跑      float64
男跳远        float64
男体前屈         int64
男引体          int64
男肺活量         int64
身高         float64
体重         float64
BMI          int64
dtype: object

In [11]:
# 男1000米跑，数据类型是str，并且是4’26这种形式，需要变成float类型的值

In [278]:
data_man['男1000米跑'] = data_man['男1000米跑'].astype(np.str).str.replace("\'",'.').astype(np.float)

In [279]:
data_mark.head()

   男肺活量       女肺活量      男50米跑      女50米跑       男体前屈       ...  女跳远        男引体  \
     成绩   分数    成绩   分数    成绩   分数    成绩   分数    成绩   分数  ...   成绩   分数    成绩
0  4540  100  3150  100   7.1  100   7.8  100  23.6  100  ...  204  100  16.0
1  4420   95  3100   95   7.2   95   7.9   95  21.5   95  ...  198   95  15.0
2  4300   90  3050   90   7.3   90   8.0   90  19.4   90  ...  192   90  14.0
3  4050   85  2900   85   7.4   85   8.3   85  17.2   85  ...  185   85  13.0
4  3800   80  2750   80   7.5   80   8.6   80  15.0   80  ...  178   80  12.0

       女仰卧      男1000米跑      女800米跑
    分数  成绩   分数      成绩   分数     成绩   分数
0  100  53  100   3'30"  100  3'24"  100
1   95  51   95   3'35"   95  3'30"   95
2   90  49   90   3'40"   90  3'36"   90
3   85  46   85   3'47"   85  3'43"   85
4   80  43   80   3'55"   80  3'50"   80

[5 rows x 24 columns]

In [280]:
# 评分标准中男1000米跑和女800米跑的成绩都是4‘10’‘这种形式，需要转化为float类型值
data_mark.loc[:,('男1000米跑','成绩')] = data_mark.loc[:,('男1000米跑','成绩')].str.replace("\'",'.').str.replace('\"','').astype(np.float)
data_mark.loc[:,('女800米跑','成绩')] = data_mark.loc[:,('女800米跑','成绩')].str.replace("\'",'.').str.replace('\"','').astype(np.float)
data_mark.head()

   男肺活量       女肺活量      男50米跑      女50米跑       男体前屈       ...  女跳远        男引体  \
     成绩   分数    成绩   分数    成绩   分数    成绩   分数    成绩   分数  ...   成绩   分数    成绩
0  4540  100  3150  100   7.1  100   7.8  100  23.6  100  ...  204  100  16.0
1  4420   95  3100   95   7.2   95   7.9   95  21.5   95  ...  198   95  15.0
2  4300   90  3050   90   7.3   90   8.0   90  19.4   90  ...  192   90  14.0
3  4050   85  2900   85   7.4   85   8.3   85  17.2   85  ...  185   85  13.0
4  3800   80  2750   80   7.5   80   8.6   80  15.0   80  ...  178   80  12.0

       女仰卧      男1000米跑      女800米跑
    分数  成绩   分数      成绩   分数     成绩   分数
0  100  53  100    3.30  100   3.24  100
1   95  51   95    3.35   95   3.30   95
2   90  49   90    3.40   90   3.36   90
3   85  46   85    3.47   85   3.43   85
4   80  43   80    3.55   80   3.50   80

[5 rows x 24 columns]

In [ ]:
# 其他所有数值类型的值，都要转换为float类型的值

In [281]:
data_mark = data_mark.astype(np.float)
data_mark

      男肺活量           女肺活量        男50米跑        女50米跑         男体前屈         ...  \
        成绩     分数      成绩     分数    成绩     分数    成绩     分数    成绩     分数  ...
0   4540.0  100.0  3150.0  100.0   7.1  100.0   7.8  100.0  23.6  100.0  ...
1   4420.0   95.0  3100.0   95.0   7.2   95.0   7.9   95.0  21.5   95.0  ...
2   4300.0   90.0  3050.0   90.0   7.3   90.0   8.0   90.0  19.4   90.0  ...
3   4050.0   85.0  2900.0   85.0   7.4   85.0   8.3   85.0  17.2   85.0  ...
4   3800.0   80.0  2750.0   80.0   7.5   80.0   8.6   80.0  15.0   80.0  ...
5   3680.0   78.0  2650.0   78.0   7.7   78.0   8.8   78.0  13.6   78.0  ...
6   3560.0   76.0  2550.0   76.0   7.9   76.0   9.0   76.0  12.2   76.0  ...
7   3440.0   74.0  2450.0   74.0   8.1   74.0   9.2   74.0  10.8   74.0  ...
8   3320.0   72.0  2350.0   72.0   8.3   72.0   9.4   72.0   9.4   72.0  ...
9   3200.0   70.0  2250.0   70.0   8.5   70.0   9.6   70.0   8.0   70.0  ...
10  3080.0   68.0  2150.0   68.0   8.7   68.0   9.8   68.0   6.6   68.0  ...
11  2960.0   66.0  2050.0   66.0   8.9   66.0  10.0   66.0   5.2   66.0  ...
12  2840.0   64.0  1950.0   64.0   9.1   64.0  10.2   64.0   3.8   64.0  ...
13  2720.0   62.0  1850.0   62.0   9.3   62.0  10.4   62.0   2.4   62.0  ...
14  2600.0   60.0  1750.0   60.0   9.5   60.0  10.6   60.0   1.0   60.0  ...
15  2470.0   50.0  1710.0   50.0   9.7   50.0  10.8   50.0   0.0   50.0  ...
16  2340.0   40.0  1670.0   40.0   9.9   40.0  11.0   40.0  -1.0   40.0  ...
17  2210.0   30.0  1630.0   30.0  10.1   30.0  11.2   30.0  -2.0   30.0  ...
18  2080.0   20.0  1590.0   20.0  10.3   20.0  11.4   20.0  -3.0   20.0  ...
19  1950.0   10.0  1550.0   10.0  10.5   10.0  11.6   10.0  -4.0   10.0  ...

      女跳远          男引体          女仰卧        男1000米跑        女800米跑
       成绩     分数    成绩     分数    成绩     分数      成绩     分数     成绩     分数
0   204.0  100.0  16.0  100.0  53.0  100.0    3.30  100.0   3.24  100.0
1   198.0   95.0  15.0   95.0  51.0   95.0    3.35   95.0   3.30   95.0
2   192.0   90.0  14.0   90.0  49.0   90.0    3.40   90.0   3.36   90.0
3   185.0   85.0  13.0   85.0  46.0   85.0    3.47   85.0   3.43   85.0
4   178.0   80.0  12.0   80.0  43.0   80.0    3.55   80.0   3.50   80.0
5   175.0   78.0   NaN   78.0  41.0   78.0    4.00   78.0   3.55   78.0
6   172.0   76.0  11.0   76.0  39.0   76.0    4.05   76.0   4.00   76.0
7   169.0   74.0   NaN   74.0  37.0   74.0    4.10   74.0   4.05   74.0
8   166.0   72.0  10.0   72.0  35.0   72.0    4.15   72.0   4.10   72.0
9   163.0   70.0   NaN   70.0  33.0   70.0    4.20   70.0   4.15   70.0
10  160.0   68.0   9.0   68.0  31.0   68.0    4.25   68.0   4.20   68.0
11  157.0   66.0   NaN   66.0  29.0   66.0    4.30   66.0   4.25   66.0
12  154.0   64.0   8.0   64.0  27.0   64.0    4.35   64.0   4.30   64.0
13  151.0   62.0   NaN   62.0  25.0   62.0    4.40   62.0   4.35   62.0
14  148.0   60.0   7.0   60.0  23.0   60.0    4.45   60.0   4.40   60.0
15  143.0   50.0   6.0   50.0  21.0   50.0    5.05   50.0   4.50   50.0
16  138.0   40.0   5.0   40.0  19.0   40.0    5.25   40.0   5.00   40.0
17  133.0   30.0   4.0   30.0  17.0   30.0    5.45   30.0   5.10   30.0
18  128.0   20.0   3.0   20.0  15.0   20.0    6.05   20.0   5.20   20.0
19  123.0   10.0   2.0   10.0  13.0   10.0    6.25   10.0   5.30   10.0

[20 rows x 24 columns]

In [282]:
data_man.iloc[:,3:] = data_man.iloc[:,3:].astype(np.float) # 第三列以后转换格式
data_man

     班级 性别  男1000米跑  男50米跑    男跳远  男体前屈   男引体    男肺活量     身高    体重  BMI
0     1  男     4.13   8.88  195.0  12.0   1.0  2785.0  170.0  72.6  0.0
1     1  男     4.16   7.70  225.0  11.0   7.0  3133.0  174.0  52.7  0.0
2     1  男     4.09   8.45  218.0  14.0   1.0  3901.0  169.0  46.5  0.0
3     1  男     4.21   8.05  206.0  13.0   1.0  4946.0  183.0  79.7  0.0
4     1  男     3.44   7.52  210.0  13.0   9.0  3538.0  171.0  54.7  0.0
..   .. ..      ...    ...    ...   ...   ...     ...    ...   ...  ...
472  17  男     4.23   8.27  208.0  10.0   0.0  4647.0  176.0  69.5  0.0
473  17  男     5.19   9.55  210.0  15.0   6.0  7042.0  177.0  76.0  0.0
474  17  男     3.25   7.50  252.0  13.0  13.0  5755.0  181.0  65.0  0.0
475  17  男     4.39   7.81  208.0  14.0  11.0  5688.0  172.0  51.7  0.0
476  17  男     0.00   0.00    0.0   0.0   0.0     0.0    0.0   0.0  0.0

[477 rows x 11 columns]

In [283]:
data_woman.iloc[:,3:] = data_woman.iloc[:,3:].astype(np.float)# 第三列以后转换格式
data_woman

     班级 性别  女800米跑  女50米跑    女跳远  女体前屈   女仰卧    女肺活量     身高    体重  BMI
0     1  女    3.22   9.32  185.0  16.0  48.0  3775.0  163.0  51.3  0.0
1     1  女    4.59  11.44  148.0   9.0  29.0  3683.0  163.0  66.6  0.0
2     1  女    3.46  13.40  150.0   7.0  40.0  3331.0  157.0  60.0  0.0
3     1  女    3.39   9.52  172.0  21.0  46.0  3701.0  160.0  50.7  0.0
4     1  女    3.43   9.79  145.0   8.0  34.0  3592.0  167.0  63.9  0.0
..   .. ..     ...    ...    ...   ...   ...     ...    ...   ...  ...
588  17  女    3.51   9.60  150.0  24.0  41.0  2255.0  158.0  49.0  0.0
589  17  女    4.00  10.18  150.0  13.0  36.0  2937.0  161.0  55.7  0.0
590  17  女    3.45  10.18  152.0  15.0  35.0  2592.0  165.0  48.6  0.0
591  17  女    4.01   9.67  165.0  10.0  41.0  1829.0  154.0  43.6  0.0
592  17  女    4.48   9.09  180.0  10.0  46.0  2962.0  162.0  55.3  0.0

[593 rows x 11 columns]

In [108]:
# 对体测成绩进行分数转换

In [284]:
data_mark.head()

     男肺活量           女肺活量        男50米跑        女50米跑         男体前屈         ...  \
       成绩     分数      成绩     分数    成绩     分数    成绩     分数    成绩     分数  ...
0  4540.0  100.0  3150.0  100.0   7.1  100.0   7.8  100.0  23.6  100.0  ...
1  4420.0   95.0  3100.0   95.0   7.2   95.0   7.9   95.0  21.5   95.0  ...
2  4300.0   90.0  3050.0   90.0   7.3   90.0   8.0   90.0  19.4   90.0  ...
3  4050.0   85.0  2900.0   85.0   7.4   85.0   8.3   85.0  17.2   85.0  ...
4  3800.0   80.0  2750.0   80.0   7.5   80.0   8.6   80.0  15.0   80.0  ...

     女跳远          男引体          女仰卧        男1000米跑        女800米跑
      成绩     分数    成绩     分数    成绩     分数      成绩     分数     成绩     分数
0  204.0  100.0  16.0  100.0  53.0  100.0    3.30  100.0   3.24  100.0
1  198.0   95.0  15.0   95.0  51.0   95.0    3.35   95.0   3.30   95.0
2  192.0   90.0  14.0   90.0  49.0   90.0    3.40   90.0   3.36   90.0
3  185.0   85.0  13.0   85.0  46.0   85.0    3.47   85.0   3.43   85.0
4  178.0   80.0  12.0   80.0  43.0   80.0    3.55   80.0   3.50   80.0

[5 rows x 24 columns]

In [258]:
# 构造打分函数
def grade(mark,performance):
    score = [] # 保存成绩
    for perform in performance:
        if perform >= mark['成绩'][0]: # 大于最大值 直接满分
            score.append(mark['分数'][0])
            continue
        if perform < mark['成绩'].iloc[-1]: # 小于最小值 直接0分
            score.append(0)
            continue
        for j in range(len(mark)-1):  
            if np.isnan(a['成绩'][j]): # 引体向上空值处理
                if mark['成绩'][j+1] <= perform < mark['成绩'][j-1]:
                    score.append(mark['分数'][j+1])
                    break
            if mark['成绩'][j+1] <= perform < mark['成绩'][j]:# ( , ] 区间内成绩
                score.append(mark['分数'][j+1])
                break
    return score

In [285]:
# 计算男肺活量成绩
score = grade(data_mark.loc[:,'男肺活量'],data_man['男肺活量'])
data_man['男肺活量成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [286]:
# 计算男跳远成绩
score = grade(data_mark.loc[:,'男跳远'],data_man['男跳远'])
data_man['男跳远成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0,66.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0,66.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0,90.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0,66.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [287]:
# 计算男体前屈成绩
score = grade(data_mark.loc[:,'男体前屈'],data_man['男体前屈'])
data_man['男体前屈成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩,男体前屈成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0,74.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0,74.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0,78.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0,76.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0,66.0,72.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0,66.0,80.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0,90.0,76.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0,66.0,78.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0

In [288]:
# 计算男引体成绩
score = grade(data_mark.loc[:,'男引体'],data_man['男引体'])
data_man['男引体成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩,男体前屈成绩,男引体成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0,74.0,0.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0,74.0,60.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0,78.0,0.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0,76.0,0.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0,76.0,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0,66.0,72.0,0.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0,66.0,80.0,50.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0,90.0,76.0,85.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0,66.0,78.0,76.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0

In [263]:
# 构造跑步打分函数
def grade_run(mark,performance):
    score = [] # 保存成绩
    for perform in performance:
        if perform <= mark['成绩'][0]: # 大于最大值 直接满分
            score.append(mark['分数'][0])
            continue
        if perform > mark['成绩'].iloc[-1]: # 小于最小值 直接0分
            score.append(0)
            continue
        for j in range(len(mark)-1):  
            if mark['成绩'][j] < perform <= mark['成绩'][j+1]:# ( , ] 区间内成绩
                score.append(mark['分数'][j+1])
                break
    return score

In [289]:
# 计算男1000米跑成绩
score = grade_run(data_mark.loc[:,'男1000米跑'],data_man['男1000米跑'])
data_man['男1000米跑成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩,男体前屈成绩,男引体成绩,男1000米跑成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0,74.0,0.0,72.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0,74.0,60.0,70.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0,78.0,0.0,74.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0,76.0,0.0,68.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0,76.0,68.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0,66.0,72.0,0.0,68.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0,66.0,80.0,50.0,40.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0,90.0,76.0,85.0,100.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0,66.0,78.0,76.0,62.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0,100.0

In [290]:
# 计算男50米跑成绩
score = grade_run(data_mark.loc[:,'男50米跑'],data_man['男50米跑'])
data_man['男50米跑成绩'] = score
data_man

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩,男体前屈成绩,男引体成绩,男1000米跑成绩,男50米跑成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0,74.0,0.0,72.0,66.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0,74.0,60.0,70.0,78.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0,78.0,0.0,74.0,70.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0,76.0,0.0,68.0,74.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0,76.0,68.0,85.0,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,17,男,4.23,8.27,208.0,10.0,0.0,4647.0,176.0,69.5,0.0,100.0,66.0,72.0,0.0,68.0,72.0
473,17,男,5.19,9.55,210.0,15.0,6.0,7042.0,177.0,76.0,0.0,100.0,66.0,80.0,50.0,40.0,50.0
474,17,男,3.25,7.50,252.0,13.0,13.0,5755.0,181.0,65.0,0.0,100.0,90.0,76.0,85.0,100.0,80.0
475,17,男,4.39,7.81,208.0,14.0,11.0,5688.0,172.0,51.7,0.0,100.0,66.0,78.0,76.0,62.0,76.0
476,17,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0,100.0,100.0

In [291]:
data_man[0:20] # 查看

,班级,性别,男1000米跑,男50米跑,男跳远,男体前屈,男引体,男肺活量,身高,体重,BMI,男肺活量成绩,男跳远成绩,男体前屈成绩,男引体成绩,男1000米跑成绩,男50米跑成绩
0,1,男,4.13,8.88,195.0,12.0,1.0,2785.0,170.0,72.6,0.0,62.0,60.0,74.0,0.0,72.0,66.0
1,1,男,4.16,7.70,225.0,11.0,7.0,3133.0,174.0,52.7,0.0,68.0,74.0,74.0,60.0,70.0,78.0
2,1,男,4.09,8.45,218.0,14.0,1.0,3901.0,169.0,46.5,0.0,80.0,70.0,78.0,0.0,74.0,70.0
3,1,男,4.21,8.05,206.0,13.0,1.0,4946.0,183.0,79.7,0.0,100.0,64.0,76.0,0.0,68.0,74.0
4,1,男,3.44,7.52,210.0,13.0,9.0,3538.0,171.0,54.7,0.0,74.0,66.0,76.0,68.0,85.0,78.0
5,1,男,3.49,7.94,190.0,20.0,7.0,3970.0,175.0,66.4,0.0,80.0,50.0,90.0,60.0,80.0,74.0
6,1,男,3.54,7.75,186.0,11.0,7.0,3710.0,173.0,53.9,0.0,78.0,40.0,74.0,60.0,80.0,76.0
7,1,男,4.30,8.06,195.0,3.0,1.0,5578.0,178.0,83.1,0.0,100.0,60.0,62.0,0.0,66.0,74.0
8,1,男,4.01,7.75,220.0,15.0,10.0,3821.0,175.0,66.5,0.0,80.0,72.0,80.0,72.0,76.0,76.0
9,1,男,4.12,7.38,245.0,17.0,11.0,4423.0,167.0,53.9,0.0,95.0,85.0,80.0,76.0,72.0,85.0
10,1,男,4.00,7.82,219.0,13.0,11.0,4031.0,173.0,57.4,0.0,80.0,72.0,76.0,76.0,78.0,76.0
11,1,男,4.13,7.37,228.0,9.0,15.0,4354.0,163.0,54.6,0.0,90.0,76.0,70.0,95.0,72.0,85.0
12,1,男,3.45,7.66,202.0,7.0,3.0,2238.0,179.0,61.1,0.0,30.0,62.0,68.0,20.0,85.0,78.0
13,1,男,3.46,7.66,245.0,3.0,7.0,4811.0,177.0,63.9,0.0,100.0,85.0,62.0,60.0,85.0,78.0
14,1,男,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0,100.0,100.0
15,1,男,3.57,7.60,192.0,7.0,5.0,4147.0,174.0,59.2,0.0,85.0,50.0,68.0,40.0,78.0,78.0
16,1,男,4.18,8.14,210.0,8.0,4.0,4241.0,179.0,61.9,0.0,85.0,66.0,70.0,30.0,70.0,72.0
17,1,男,3.32,7.20,255.0,22.0,12.0,5324.0,183.0,63.4,0.0,100.0,90.0,95.0,80.0,95.0,95.0
18,1,男,3.56,8.15,207.0,13.0,12.0,4363.0,173.0,60.5,0.0,90.0,64.0,76.0,80.0,78.0,72.0
19,1,男,3.47,8.15,202.0,13.0,16.0,5364.0,174.0,56.0,0.0,100.0,62.0,76.0,100.0,85.0,72.0

In [310]:
# 调换列顺序
clos = ['班级', '性别', '男1000米跑','男1000米跑成绩', '男50米跑', '男50米跑成绩',
        '男跳远', '男跳远成绩', '男体前屈', '男体前屈成绩',  '男引体', '男引体成绩',
        '男肺活量',  '男肺活量成绩', '身高','体重','BMI']
data_man = data_man[clos]

In [293]:
data_woman.head()

   班级 性别  女800米跑  女50米跑    女跳远  女体前屈   女仰卧    女肺活量     身高    体重  BMI
0   1  女    3.22   9.32  185.0  16.0  48.0  3775.0  163.0  51.3  0.0
1   1  女    4.59  11.44  148.0   9.0  29.0  3683.0  163.0  66.6  0.0
2   1  女    3.46  13.40  150.0   7.0  40.0  3331.0  157.0  60.0  0.0
3   1  女    3.39   9.52  172.0  21.0  46.0  3701.0  160.0  50.7  0.0
4   1  女    3.43   9.79  145.0   8.0  34.0  3592.0  167.0  63.9  0.0

In [301]:
# 女800米成绩
score = grade_run(data_mark.loc[:,'女800米跑'],data_woman['女800米跑'])
data_woman['女800米跑成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0

In [302]:
# 女50米成绩
score = grade_run(data_mark.loc[:,'女50米跑'],data_woman['女50米跑'])
data_woman['女50米跑成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0

In [303]:
# 女跳远成绩
score = grade(data_mark.loc[:,'女跳远'],data_woman['女跳远'])
data_woman['女跳远成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0

In [304]:
# 女体前屈成绩
score = grade(data_mark.loc[:,'女体前屈'],data_woman['女体前屈'])
data_woman['女体前屈成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩,女体前屈成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0,76.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0,66.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0,64.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0,90.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0,95.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0,72.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0,68.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0,68.0

In [305]:
# 女仰卧成绩
score = grade(data_mark.loc[:,'女仰卧'],data_woman['女仰卧'])
data_woman['女仰卧成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩,女体前屈成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0,76.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0,66.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0,64.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0,90.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0,95.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0,72.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0,68.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0,68.0

In [306]:
# 女肺活量成绩
score = grade(data_mark.loc[:,'女肺活量'],data_woman['女肺活量'])
data_woman['女肺活量成绩'] = score
data_woman

,班级,性别,女800米跑,女50米跑,女跳远,女体前屈,女仰卧,女肺活量,身高,体重,BMI,女800米跑成绩,女50米跑成绩,女跳远成绩,女仰卧成绩,女肺活量成绩,女体前屈成绩
0,1,女,3.22,9.32,185.0,16.0,48.0,3775.0,163.0,51.3,0.0,100.0,72.0,85.0,85.0,100.0,76.0
1,1,女,4.59,11.44,148.0,9.0,29.0,3683.0,163.0,66.6,0.0,40.0,10.0,60.0,66.0,100.0,66.0
2,1,女,3.46,13.40,150.0,7.0,40.0,3331.0,157.0,60.0,0.0,80.0,0.0,60.0,76.0,100.0,64.0
3,1,女,3.39,9.52,172.0,21.0,46.0,3701.0,160.0,50.7,0.0,85.0,70.0,76.0,85.0,100.0,90.0
4,1,女,3.43,9.79,145.0,8.0,34.0,3592.0,167.0,63.9,0.0,85.0,68.0,50.0,70.0,100.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,17,女,3.51,9.60,150.0,24.0,41.0,2255.0,158.0,49.0,0.0,78.0,70.0,60.0,78.0,70.0,95.0
589,17,女,4.00,10.18,150.0,13.0,36.0,2937.0,161.0,55.7,0.0,76.0,64.0,60.0,72.0,85.0,72.0
590,17,女,3.45,10.18,152.0,15.0,35.0,2592.0,165.0,48.6,0.0,80.0,64.0,62.0,72.0,76.0,76.0
591,17,女,4.01,9.67,165.0,10.0,41.0,1829.0,154.0,43.6,0.0,74.0,68.0,70.0,78.0,60.0,68.0
592,17,女,4.48,9.09,180.0,10.0,46.0,2962.0,162.0,55.3,0.0,50.0,74.0,80.0,85.0,85.0,68.0

In [309]:
# 调换列顺序
clos = ['班级', '性别', '女800米跑','女800米跑成绩', '女50米跑', '女50米跑成绩',
        '女跳远', '女跳远成绩', '女体前屈', '女体前屈成绩',  '女仰卧', '女仰卧成绩',
        '女肺活量',  '女肺活量成绩', '身高','体重','BMI']
data_woman = data_woman[clos]

In [311]:
# 综上 结果查看
display(data_man[0:50],data_woman[0:50])

,班级,性别,男1000米跑,男1000米跑成绩,男50米跑,男50米跑成绩,男跳远,男跳远成绩,男体前屈,男体前屈成绩,男引体,男引体成绩,男肺活量,男肺活量成绩,身高,体重,BMI
0,1,男,4.13,72.0,8.88,66.0,195.0,60.0,12.0,74.0,1.0,0.0,2785.0,62.0,170.000000,72.6,0.0
1,1,男,4.16,70.0,7.70,78.0,225.0,74.0,11.0,74.0,7.0,60.0,3133.0,68.0,174.000000,52.7,0.0
2,1,男,4.09,74.0,8.45,70.0,218.0,70.0,14.0,78.0,1.0,0.0,3901.0,80.0,169.000000,46.5,0.0
3,1,男,4.21,68.0,8.05,74.0,206.0,64.0,13.0,76.0,1.0,0.0,4946.0,100.0,183.000000,79.7,0.0
4,1,男,3.44,85.0,7.52,78.0,210.0,66.0,13.0,76.0,9.0,68.0,3538.0,74.0,171.000000,54.7,0.0
5,1,男,3.49,80.0,7.94,74.0,190.0,50.0,20.0,90.0,7.0,60.0,3970.0,80.0,175.000000,66.4,0.0
6,1,男,3.54,80.0,7.75,76.0,186.0,40.0,11.0,74.0,7.0,60.0,3710.0,78.0,173.000000,53.9,0.0
7,1,男,4.30,66.0,8.06,74.0,195.0,60.0,3.0,62.0,1.0,0.0,5578.0,100.0,178.000000,83.1,0.0
8,1,男,4.01,76.0,7.75,76.0,220.0,72.0,15.0,80.0,10.0,72.0,3821.0,80.0,175.000000,66.5,0.0
9,1,男,4.12,72.0,7.38,85.0,245.0,85.0,17.0,80.0,11.0,76.0,4423.0,95.0,167.000000,53.9,0.0
10,1,男,4.00,78.0,7.82,76.0,219.0,72.0,13.0,76.0,11.0,76.0,4031.0,80.0,173.000000,57.4,0.0
11,1,男,4.13,72.0,7.37,85.0,228.0,76.0,9.0,70.0,15.0,95.0,4354.0,90.0,163.000000,54.6,0.0
12,1,男,3.45,85.0,7.66,78.0,202.0,62.0,7.0,68.0,3.0,20.0,2238.0,30.0,179.000000,61.1,0.0
13,1,男,3.46,85.0,7.66,78.0,245.0,85.0,3.0,62.0,7.0,60.0,4811.0,100.0,177.000000,63.9,0.0
14,1,男,0.00,100.0,0.00,100.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
15,1,男,3.57,78.0,7.60,78.0,192.0,50.0,7.0,68.0,5.0,40.0,4147.0,85.0,174.000000,59.2,0.0
16,1,男,4.18,70.0,8.14,72.0,210.0,66.0,8.0,70.0,4.0,30.0,4241.0,85.0,179.000000,61.9,0.0
17,1,男,3.32,95.0,7.20,95.0,255.0,90.0,22.0,95.0,12.0,80.0,5324.0,100.0,183.000000,63.4,0.0
18,1,男,3.56,78.0,8.15,72.0,207.0,64.0,13.0,76.0,12.0,80.0,4363.0,90.0,173.000000,60.5,0.0
19,1,男,3.47,85.0,8.15,72.0,202.0,62.0,13.0,76.0,16.0,100.0,5364.0,100.0,174.000000,56.0,0.0
20,1,男,3.53,80.0,7.85,76.0,210.0,66.0,3.0,62.0,7.0,60.0,3445.0,74.0,177.000000,56.9,0.0
21,1,男,3.57,78.0,7.85,76.0,220.0,72.0,9.0,70.0,2.0,10.0,5670.0,100.0,177.000000,55.5,0.0
22,1,男,3.42,85.0,7.23,90.0,212.0,68.0,12.0,74.0,15.0,95.0,5709.0,100.0,185.000000,72.3,0.0
23,1,男,4.30,66.0,7.68,78.0,218.0,70.0,15.0,80.0,3.0,20.0,4780.0,100.0,177.000000,83.7,0.0
24,1,男,4.14,72.0,8.30,72.0,206.0,64.0,15.0,80.0,1.0,0.0,3358.0,72.0,173.000000,46.6,0.0
25,1,男,4.04,76.0,8.15,72.0,205.0,64.0,9.0,70.0,5.0,40.0,3494.0,74.0,169.000000,48.3,0.0
26,1,男,4.04,76.0,7.55,78.0,190.0,50.0,12.0,74.0,5.0,40.0,3286.0,70.0,169.000000,50.1,0.0
27,1,男,4.02,76.0,7.55,78.0,240.0,80.0,5.0,64.0,12.0,80.0,4483.0,95.0,171.000000,58.4,0.0
28,1,男,3.57,78.0,7.89,76.0,220.0,72.0,9.0,70.0,11.0,76.0,4254.0,85.0,166.000000,54.8,0.0
29,1,男,4.16,70.0,8.19,72.0,212.0,68.0,27.0,100.0,7.0,60.0,3498.0,74.0,169.000000,68.0,0.0
30,1,男,4.01,76.0,7.89,76.0,213.0,68.0,5.0,64.0,11.0,76.0,4322.0,90.0,174.000000,55.9,0.0
31,1,男,4.08,74.0,8.21,72.0,208.0,66.0,19.0,85.0,20.0,100.0,3917.0,80.0,166.000000,51.9,0.0
32,1,男,4.06,74.0,8.71,66.0,206.0,64.0,11.0,74.0,4.0,30.0,3970.0,80.0,172.000000,47.8,0.0
33,2,男,4.22,68.0,7.97,74.0,215.0,70.0,9.0,70.0,9.0,68.0,3865.0,80.0,175.000000,58.7,0.0
34,2,男,0.00,100.0,0.00,100.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
35,2,男,4.46,50.0,8.79,66.0,172.0,10.0,7.0,68.0,1.0,0.0,4750.0,100.0,174.000000,88.6,0.0
36,2,男,4.01,76.0,7.37,85.0,210.0,66.0,2.0,60.0,7.0,60.0,4714.0,100.0,182.000000,62.5,0.0
37,2,男,0.00,100.0,0.00,100.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
38,2,男,4.13,72.0,7.77,76.0,208.0,66.0,8.0,70.0,7.0,60.0,4327.0,90.0,173.000000,56.0,0.0
39,2,男,4.27,66.0,8.80,66.0,185.0,40.0,10.0,72.0,5.0,40.0,4745.0,100.0,164.000000,74.8,0.0
40,3,男,3.43,85.0,6.89,100.0,276.0,100.0,16.0,80.0,12.0,80.0,5212.0,100.0,184.000003,73.1,0.0
41,3,男,4.04,76.0,7.25,90.0,240.0,80.0,13.0,76.0,8.0,64.0,4756.0,100.0,175.999999,72.0,0.0
42,3,男,3.38,90.0,7.36,85.0,246.0,85.0,22.0,95.0,11.0,76.0,4433.0,95.0,184.000003,62.5,0.0
43,3,男,4.19,70.0,8.17,72.0,220.0,72.0,18.0,85.0,1.0,0.0,4438.0,95.0,174.000001,72.2,0.0
44,3,男,4.08,74.0,7.80,76.0,227.0,76.0,15.0,80.0,1.0,0.0,6033.0,100.0,176.999998,85.6,0.0
45,3,男,4.09,74.0,8.06,74.0,208.0,66.0,10.0,72.0,2.0,10.0,4106.0,85.0,170.000005,68.7,0.0
46,3,男,4.09,74.0,8.16,72.0,190.0,50.0,2.0,60.0,6.0,50.0,4214.0,85.0,166.999996,60.7,0.0
47,3,男,4.05,76.0,8.16,72.0,200.0,62.0,13.0,76.0,9.0,68.0,3857.0,80.0,172.000003,51.4,0.0
48,3,男,4.02,76.0,8.27,72.0,228.0,76.0,14.0,78.0,12.0,80.0,3266.0,70.0,162.000000,52.2,0.0
49,3,男,4.10,74.0,8.50,70.0,215.0,70.0,6.0,66.0,9.0,68.0,3578.0,76.0,163.999999,49.9,0.0

,班级,性别,女800米跑,女800米跑成绩,女50米跑,女50米跑成绩,女跳远,女跳远成绩,女体前屈,女体前屈成绩,女仰卧,女仰卧成绩,女肺活量,女肺活量成绩,身高,体重,BMI
0,1,女,3.22,100.0,9.32,72.0,185.0,85.0,16.0,76.0,48.0,85.0,3775.0,100.0,163.0,51.3,0.0
1,1,女,4.59,40.0,11.44,10.0,148.0,60.0,9.0,66.0,29.0,66.0,3683.0,100.0,163.0,66.6,0.0
2,1,女,3.46,80.0,13.40,0.0,150.0,60.0,7.0,64.0,40.0,76.0,3331.0,100.0,157.0,60.0,0.0
3,1,女,3.39,85.0,9.52,70.0,172.0,76.0,21.0,90.0,46.0,85.0,3701.0,100.0,160.0,50.7,0.0
4,1,女,3.43,85.0,9.79,68.0,145.0,50.0,8.0,64.0,34.0,70.0,3592.0,100.0,167.0,63.9,0.0
5,1,女,3.47,80.0,10.01,64.0,158.0,66.0,17.0,78.0,35.0,72.0,3483.0,100.0,170.0,47.0,0.0
6,1,女,4.69,40.0,10.42,60.0,150.0,60.0,18.0,80.0,32.0,68.0,3754.0,100.0,158.0,54.0,0.0
7,1,女,4.26,64.0,10.03,64.0,165.0,70.0,16.0,76.0,35.0,72.0,4520.0,100.0,160.0,48.5,0.0
8,1,女,3.48,80.0,10.59,60.0,159.0,66.0,8.0,64.0,46.0,85.0,3662.0,100.0,160.0,42.0,0.0
9,1,女,4.18,68.0,10.30,62.0,161.0,68.0,22.0,90.0,42.0,78.0,3955.0,100.0,171.0,62.2,0.0
10,1,女,3.38,85.0,9.37,72.0,162.0,68.0,15.0,76.0,43.0,80.0,4374.0,100.0,157.0,56.0,0.0
11,1,女,4.11,70.0,10.68,50.0,150.0,60.0,15.0,76.0,45.0,80.0,4488.0,100.0,175.0,53.2,0.0
12,1,女,3.45,80.0,9.74,68.0,168.0,72.0,21.0,90.0,35.0,72.0,4176.0,100.0,164.0,49.5,0.0
13,1,女,3.59,76.0,10.83,40.0,140.0,40.0,6.0,62.0,41.0,78.0,3497.0,100.0,159.0,52.0,0.0
14,1,女,3.32,90.0,10.25,62.0,167.0,72.0,19.0,80.0,31.0,68.0,4094.0,100.0,165.0,56.7,0.0
15,1,女,3.40,85.0,10.25,62.0,152.0,62.0,21.0,90.0,43.0,80.0,3403.0,100.0,156.0,50.9,0.0
16,1,女,3.58,76.0,9.85,66.0,160.0,68.0,14.0,74.0,29.0,66.0,4433.0,100.0,172.0,77.6,0.0
17,1,女,3.36,90.0,9.41,70.0,182.0,80.0,24.0,95.0,30.0,66.0,4520.0,100.0,167.0,61.6,0.0
18,1,女,3.48,80.0,9.44,70.0,176.0,78.0,17.0,78.0,43.0,80.0,4209.0,100.0,157.0,57.1,0.0
19,1,女,3.24,100.0,9.07,74.0,185.0,85.0,22.0,90.0,33.0,70.0,2887.0,80.0,167.0,52.0,0.0
20,1,女,3.48,80.0,10.00,66.0,160.0,68.0,18.0,80.0,30.0,66.0,3016.0,85.0,157.0,55.7,0.0
21,1,女,4.09,72.0,10.00,66.0,172.0,76.0,8.0,64.0,42.0,78.0,3949.0,100.0,172.0,57.8,0.0
22,1,女,3.30,95.0,9.74,68.0,155.0,64.0,10.0,68.0,35.0,72.0,3574.0,100.0,155.0,52.2,0.0
23,1,女,3.35,90.0,9.74,68.0,180.0,80.0,19.0,80.0,33.0,70.0,3285.0,100.0,161.0,51.3,0.0
24,1,女,4.03,74.0,10.80,50.0,151.0,62.0,11.0,70.0,40.0,76.0,3503.0,100.0,162.0,50.6,0.0
25,1,女,3.40,85.0,9.95,66.0,168.0,72.0,15.0,76.0,41.0,78.0,4586.0,100.0,166.0,53.3,0.0
26,1,女,3.58,76.0,9.68,68.0,186.0,85.0,21.0,90.0,40.0,76.0,3942.0,100.0,161.0,51.3,0.0
27,1,女,3.49,80.0,8.77,78.0,185.0,85.0,19.0,80.0,40.0,76.0,3171.0,100.0,160.0,46.7,0.0
28,2,女,0.00,100.0,10.10,64.0,150.0,60.0,30.0,100.0,28.0,64.0,2673.0,78.0,169.0,61.0,0.0
29,2,女,4.19,68.0,9.90,66.0,151.0,62.0,20.0,85.0,32.0,68.0,3410.0,100.0,165.0,65.6,0.0
30,2,女,4.10,72.0,9.86,66.0,160.0,68.0,20.0,85.0,43.0,80.0,1849.0,60.0,163.0,59.7,0.0
31,2,女,4.12,70.0,9.99,66.0,150.0,60.0,21.0,90.0,43.0,80.0,3122.0,95.0,159.0,62.4,0.0
32,2,女,3.29,95.0,9.33,72.0,155.0,64.0,8.0,64.0,38.0,74.0,2369.0,72.0,155.0,48.3,0.0
33,2,女,4.16,68.0,9.66,68.0,140.0,40.0,11.0,70.0,40.0,76.0,2712.0,78.0,169.0,49.3,0.0
34,2,女,4.15,70.0,10.27,62.0,150.0,60.0,15.0,76.0,41.0,78.0,2308.0,70.0,162.0,52.4,0.0
35,2,女,3.55,78.0,9.59,70.0,175.0,78.0,30.0,100.0,31.0,68.0,3166.0,100.0,166.0,47.5,0.0
36,2,女,3.51,78.0,9.54,70.0,150.0,60.0,11.0,70.0,40.0,76.0,3187.0,100.0,169.0,56.6,0.0
37,2,女,3.32,90.0,8.71,78.0,181.0,80.0,13.0,72.0,37.0,74.0,2669.0,78.0,167.0,50.0,0.0
38,2,女,3.45,80.0,9.05,74.0,152.0,62.0,18.0,80.0,40.0,76.0,3122.0,95.0,160.0,61.2,0.0
39,2,女,3.48,80.0,8.70,78.0,210.0,100.0,18.0,80.0,49.0,90.0,2928.0,85.0,163.0,50.0,0.0
40,2,女,4.05,74.0,9.48,70.0,160.0,68.0,17.0,78.0,43.0,80.0,3125.0,95.0,165.0,53.4,0.0
41,2,女,4.04,74.0,9.70,68.0,168.0,72.0,16.0,76.0,42.0,78.0,2089.0,66.0,154.0,35.7,0.0
42,2,女,3.42,85.0,9.10,74.0,158.0,66.0,16.0,76.0,42.0,78.0,2106.0,66.0,159.0,45.3,0.0
43,2,女,3.58,76.0,9.67,68.0,180.0,80.0,28.0,100.0,45.0,80.0,3102.0,95.0,159.0,53.2,0.0
44,2,女,3.47,80.0,9.83,66.0,152.0,62.0,24.0,95.0,45.0,80.0,3056.0,90.0,171.0,69.1,0.0
45,2,女,3.37,85.0,9.83,66.0,150.0,60.0,7.0,64.0,45.0,80.0,2411.0,72.0,159.0,44.9,0.0
46,2,女,3.49,80.0,9.65,68.0,161.0,68.0,16.0,76.0,41.0,78.0,3782.0,100.0,167.0,60.2,0.0
47,2,女,3.26,95.0,9.02,74.0,167.0,72.0,18.0,80.0,35.0,72.0,2388.0,72.0,158.0,52.7,0.0
48,2,女,3.08,100.0,9.80,68.0,140.0,40.0,11.0,70.0,38.0,74.0,2576.0,76.0,174.0,61.4,0.0
49,2,女,4.01,74.0,9.90,66.0,151.0,62.0,18.0,80.0,35.0,72.0,2742.0,78.0,160.0,50.8,0.0